# Running Configuration
server:
  port: ${SERVER_PORT:8080}

#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DATASOURCE_URL}:${DATASOURCE_PORT}/${DATASOURCE_DATABASE}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#  thymeleaf: # Thymeleaf
#    cache: false